name: Android Emulator Test

on:
  push:
    branches:
      - homologacao


jobs:
  run-emulator:
    runs-on: ubuntu-latest

    steps:
      # Verifique se a ação foi acionada
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar o Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Baixar o Android SDK
      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools-linux.zip
          sudo mkdir -p /usr/local/android-sdk/cmdline-tools
          sudo unzip -q commandlinetools-linux.zip -d /usr/local/android-sdk/cmdline-tools
          export ANDROID_HOME=/usr/local/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-34" "build-tools;34.0.0" "system-images;android-30;google_apis;x86_64" "emulator"

      # Criar e iniciar o emulador
      - name: Start Android Emulator
        run: |
          export ANDROID_HOME=/usr/local/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator
          echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force
          $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-window -gpu swiftshader_indirect &

      # Aguardar o emulador iniciar
      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          adb shell input keyevent 82